export enum ElementLabel {
  MARBLE = "marble",
  EARTH = "earth",
  GROUND = "ground",
  ELEVATOR = "elevator",
  ELEVATOR_PIVOTS = "elevators",
  LIFT= "LIFT",
  ELEVATOR_BUCKET = "elevatorbucket",
  TRAPDOOR = "trapdoor",
  TRAPDOOR_SLIDER = "trapdoorslider",
  DESTROYER = "destroyer",
  DESTROYER_CIRCLES = "destroyercircles",
  CAR= "car",
  RAMP = "ramp",
  WEIGHT = "weight",
}
